version: '3'
services:
  mariadb:
    hostname: mariadb
    # as of 2025/2, 11.4 is the latest LTS release supported through 2029/5
    image: "mariadb:11.4.5"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: timeboxing
      MYSQL_USER: tbuser
      MYSQL_PASSWORD: password
    volumes:
      - "/var/lib/mysql/data"
      - "/var/lib/mysql/logs"
      - "/var/docker/mariadb/conf:/etc/mysql"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 2
  flyway:
    image: flyway/flyway:10-alpine
    command: -url=jdbc:mariadb://mariadb1:3306/timeboxing  -user=tbuser -password=password migrate
    volumes:
      - ./domain-dal/domain-dal-mariadb/migrations:/flyway/sql
    depends_on:
      mariadb:
        condition: service_healthy
  smtp:
    image: "inbucket/inbucket:sha-2d409bb"
    ports:
      - "9000:9000"
  webapp:
    build: ./webapp/.
    environment:
      JPDA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=0.0.0.0:8000,server=y,suspend=n"
    depends_on:
      - mariadb
      - flyway
      - smtp
    volumes:
      - "/usr/local/tomcat/logs/"
    ports:
      - "8080:8080"
      - "8000:8000"
    entrypoint: "/usr/local/tomcat/bin/catalina.sh jpda run"